name: project-odysseus
region: fra
domains:
  - domain: projectodysseus.live
    type: PRIMARY
  - domain: www.projectodysseus.live
    type: ALIAS

static_sites:
  - name: website
    build_command: npm ci && npm run build
    output_dir: dist
    github:
      repo: JustTryingToDoBetter/LJ-s-tutoring
      branch: main
      deploy_on_push: true
    routes:
      - path: /
    catchall_document: 404.html
    environment_slug: html
